import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ReduxProvider } from "./providers";

export const metadata: Metadata = {
  title: "Letscode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-black text-white">
        <ReduxProvider>
          <div className="flex flex-col h-screen">
            <Navbar />
            <main className="grow flex">{children}</main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
