services:
  postgres:
    image: postgres:16
    container_name: letscode-postgres
    env_file:
      - .env.server
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  server:
    build: ./server
    container_name: letscode-server
    env_file:
      - .env.server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  
  client:
    build: ./client
    container_name: letscode-client
    env_file:
      - .env.client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  pgdata: