services:
  postgres:
    image: postgres:16
    container_name: letscode-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  redis:
    image: redis:7
    container_name: letscode-redis
    ports:
      - 6379:6379
  
  gateway:
    build:
      context: ../apps/gateway
      dockerfile: Dockerfile.dev
    container_name: letscode-gateway
    ports:
      - "${GATEWAY_PORT}:5000"
    volumes:
      - ../apps/gateway:/app
    depends_on:
      - redis
  
  auth:
    build:
      context: ../apps/auth
      dockerfile: Dockerfile.dev
    container_name: letscode-auth
    env_file:
      - ../.env
    volumes:
      - ../apps/auth:/app
    depends_on:
      - postgres
      - redis

volumes:
  pgdata: